#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Switch between applications in workspace
##?
##? Usage:
##?    switch
docs::parse "$@"

ls ~/Projects | rofi -show -dmenu -font "Monospace 10" -i | xargs -I_ code ~/Projects/_